# Stork configuration file"
path                    "./specs/stork"
bundle_path             "./specs/stork/bundles"
authorized_keys_file    "./specs/stork/authorized_keys"
pxe_path                "./specs/tmp/pxeboot"
log_file                "./specs/tmp/stork.log"
pid_file                "./specs/tmp/stork.pid"
server                  "localhost"
port                    5000
bind                    "0.0.0.0"
timezone                "America/New_York"
